--[[
    init.lua
    Created: 07/06/2024 20:12:47
    Description: Autogenerated script file for the map hub.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local hub = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---hub.Init(zone)
--Engine callback function
function hub.Init(zone)


end

---hub.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function hub.EnterSegment(zone, rescuing, segmentID, mapID)


end

---hub.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function hub.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---hub.Rescued(zone, name, mail)
--Engine callback function
function hub.Rescued(zone, name, mail)


end

return hub

