--[[
    init.lua
    Created: 07/13/2024 12:15:09
    Description: Autogenerated script file for the map hot_spring.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local hot_spring = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---hot_spring.Init(map)
--Engine callback function
function hot_spring.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---hot_spring.Enter(map)
--Engine callback function
function hot_spring.Enter(map)

  GAME:FadeIn(20)

end

---hot_spring.Exit(map)
--Engine callback function
function hot_spring.Exit(map)


end

---hot_spring.Update(map)
--Engine callback function
function hot_spring.Update(map)


end

---hot_spring.GameSave(map)
--Engine callback function
function hot_spring.GameSave(map)


end

---hot_spring.GameLoad(map)
--Engine callback function
function hot_spring.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return hot_spring

