--[[
    init.lua
    Created: 08/27/2024 18:39:37
    Description: Autogenerated script file for the map foggy_forest_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local foggy_forest_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---foggy_forest_entrance.Init(map)
--Engine callback function
function foggy_forest_entrance.Init(map)


end

---foggy_forest_entrance.Enter(map)
--Engine callback function
function foggy_forest_entrance.Enter(map)

  GAME:FadeIn(20)

end

---foggy_forest_entrance.Exit(map)
--Engine callback function
function foggy_forest_entrance.Exit(map)


end

---foggy_forest_entrance.Update(map)
--Engine callback function
function foggy_forest_entrance.Update(map)


end

---foggy_forest_entrance.GameSave(map)
--Engine callback function
function foggy_forest_entrance.GameSave(map)


end

---foggy_forest_entrance.GameLoad(map)
--Engine callback function
function foggy_forest_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return foggy_forest_entrance

