--[[
    init.lua
    Created: 08/26/2024 19:21:13
    Description: Autogenerated script file for the map apple_woods_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local apple_woods_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---apple_woods_entrance.Init(map)
--Engine callback function
function apple_woods_entrance.Init(map)


end

---apple_woods_entrance.Enter(map)
--Engine callback function
function apple_woods_entrance.Enter(map)

  GAME:FadeIn(20)

end

---apple_woods_entrance.Exit(map)
--Engine callback function
function apple_woods_entrance.Exit(map)


end

---apple_woods_entrance.Update(map)
--Engine callback function
function apple_woods_entrance.Update(map)


end

---apple_woods_entrance.GameSave(map)
--Engine callback function
function apple_woods_entrance.GameSave(map)


end

---apple_woods_entrance.GameLoad(map)
--Engine callback function
function apple_woods_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return apple_woods_entrance

