--[[
    init.lua
    Created: 09/27/2024 21:20:25
    Description: Autogenerated script file for the map Dusknoir_Boss_Arena.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Dusknoir_Boss_Arena = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Dusknoir_Boss_Arena.Init(map)
--Engine callback function
function Dusknoir_Boss_Arena.Init(map)


end

---Dusknoir_Boss_Arena.Enter(map)
--Engine callback function
function Dusknoir_Boss_Arena.Enter(map)

  GAME:FadeIn(20)

end

---Dusknoir_Boss_Arena.Exit(map)
--Engine callback function
function Dusknoir_Boss_Arena.Exit(map)


end

---Dusknoir_Boss_Arena.Update(map)
--Engine callback function
function Dusknoir_Boss_Arena.Update(map)


end

---Dusknoir_Boss_Arena.GameSave(map)
--Engine callback function
function Dusknoir_Boss_Arena.GameSave(map)


end

---Dusknoir_Boss_Arena.GameLoad(map)
--Engine callback function
function Dusknoir_Boss_Arena.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Dusknoir_Boss_Arena

