--[[
    init.lua
    Created: 09/26/2024 17:49:48
    Description: Autogenerated script file for the map Treeshroud_Forest_End_Normal.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Treeshroud_Forest_End_Normal = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Treeshroud_Forest_End_Normal.Init(map)
--Engine callback function
function Treeshroud_Forest_End_Normal.Init(map)


end

---Treeshroud_Forest_End_Normal.Enter(map)
--Engine callback function
function Treeshroud_Forest_End_Normal.Enter(map)

  GAME:FadeIn(20)

end

---Treeshroud_Forest_End_Normal.Exit(map)
--Engine callback function
function Treeshroud_Forest_End_Normal.Exit(map)


end

---Treeshroud_Forest_End_Normal.Update(map)
--Engine callback function
function Treeshroud_Forest_End_Normal.Update(map)


end

---Treeshroud_Forest_End_Normal.GameSave(map)
--Engine callback function
function Treeshroud_Forest_End_Normal.GameSave(map)


end

---Treeshroud_Forest_End_Normal.GameLoad(map)
--Engine callback function
function Treeshroud_Forest_End_Normal.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Treeshroud_Forest_End_Normal

