--[[
    init.lua
    Created: 10/05/2024 10:33:10
    Description: Autogenerated script file for the map mystifying_forest_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local mystifying_forest_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mystifying_forest_entrance.Init(map)
--Engine callback function
function mystifying_forest_entrance.Init(map)


end

---mystifying_forest_entrance.Enter(map)
--Engine callback function
function mystifying_forest_entrance.Enter(map)

  GAME:FadeIn(20)

end

---mystifying_forest_entrance.Exit(map)
--Engine callback function
function mystifying_forest_entrance.Exit(map)


end

---mystifying_forest_entrance.Update(map)
--Engine callback function
function mystifying_forest_entrance.Update(map)


end

---mystifying_forest_entrance.GameSave(map)
--Engine callback function
function mystifying_forest_entrance.GameSave(map)


end

---mystifying_forest_entrance.GameLoad(map)
--Engine callback function
function mystifying_forest_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mystifying_forest_entrance

