--[[
    init.lua
    Created: 10/05/2024 11:27:40
    Description: Autogenerated script file for the map mt_travail_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local mt_travail_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mt_travail_entrance.Init(map)
--Engine callback function
function mt_travail_entrance.Init(map)


end

---mt_travail_entrance.Enter(map)
--Engine callback function
function mt_travail_entrance.Enter(map)

  GAME:FadeIn(20)

end

---mt_travail_entrance.Exit(map)
--Engine callback function
function mt_travail_entrance.Exit(map)


end

---mt_travail_entrance.Update(map)
--Engine callback function
function mt_travail_entrance.Update(map)


end

---mt_travail_entrance.GameSave(map)
--Engine callback function
function mt_travail_entrance.GameSave(map)


end

---mt_travail_entrance.GameLoad(map)
--Engine callback function
function mt_travail_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mt_travail_entrance

