--[[
    init.lua
    Created: 09/06/2024 12:59:52
    Description: Autogenerated script file for the map crystal_crossing_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crystal_crossing_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_crossing_entrance.Init(map)
--Engine callback function
function crystal_crossing_entrance.Init(map)


end

---crystal_crossing_entrance.Enter(map)
--Engine callback function
function crystal_crossing_entrance.Enter(map)

  GAME:FadeIn(20)

end

---crystal_crossing_entrance.Exit(map)
--Engine callback function
function crystal_crossing_entrance.Exit(map)


end

---crystal_crossing_entrance.Update(map)
--Engine callback function
function crystal_crossing_entrance.Update(map)


end

---crystal_crossing_entrance.GameSave(map)
--Engine callback function
function crystal_crossing_entrance.GameSave(map)


end

---crystal_crossing_entrance.GameLoad(map)
--Engine callback function
function crystal_crossing_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_crossing_entrance

