--[[
    init.lua
    Created: 09/06/2024 22:32:45
    Description: Autogenerated script file for the map dusk_forest_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local dusk_forest_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---dusk_forest_entrance.Init(map)
--Engine callback function
function dusk_forest_entrance.Init(map)


end

---dusk_forest_entrance.Enter(map)
--Engine callback function
function dusk_forest_entrance.Enter(map)

  GAME:FadeIn(20)

end

---dusk_forest_entrance.Exit(map)
--Engine callback function
function dusk_forest_entrance.Exit(map)


end

---dusk_forest_entrance.Update(map)
--Engine callback function
function dusk_forest_entrance.Update(map)


end

---dusk_forest_entrance.GameSave(map)
--Engine callback function
function dusk_forest_entrance.GameSave(map)


end

---dusk_forest_entrance.GameLoad(map)
--Engine callback function
function dusk_forest_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return dusk_forest_entrance

