--[[
    init.lua
    Created: 08/26/2024 20:02:15
    Description: Autogenerated script file for the map apple_woods_end.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local apple_woods_end = {}

-------------------------------
-- Map Callbacks
-------------------------------
---apple_woods_end.Init(map)
--Engine callback function
function apple_woods_end.Init(map)


end

---apple_woods_end.Enter(map)
--Engine callback function
function apple_woods_end.Enter(map)

  GAME:FadeIn(20)

end

---apple_woods_end.Exit(map)
--Engine callback function
function apple_woods_end.Exit(map)


end

---apple_woods_end.Update(map)
--Engine callback function
function apple_woods_end.Update(map)


end

---apple_woods_end.GameSave(map)
--Engine callback function
function apple_woods_end.GameSave(map)


end

---apple_woods_end.GameLoad(map)
--Engine callback function
function apple_woods_end.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return apple_woods_end

