--[[
    init.lua
    Created: 11/22/2023 12:35:04
    Description: Autogenerated script file for the map guild_basement.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local guild_basement = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_basement.Init(map)
--Engine callback function
function guild_basement.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---guild_basement.Enter(map)
--Engine callback function
function guild_basement.Enter(map)

  GAME:FadeIn(20)

end

---guild_basement.Exit(map)
--Engine callback function
function guild_basement.Exit(map)


end

---guild_basement.Update(map)
--Engine callback function
function guild_basement.Update(map)


end

---guild_basement.GameSave(map)
--Engine callback function
function guild_basement.GameSave(map)


end

---guild_basement.GameLoad(map)
--Engine callback function
function guild_basement.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return guild_basement

