--[[
    init.lua
    Created: 10/05/2024 11:58:57
    Description: Autogenerated script file for the map darkrai_boss_arena.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local darkrai_boss_arena = {}

-------------------------------
-- Map Callbacks
-------------------------------
---darkrai_boss_arena.Init(map)
--Engine callback function
function darkrai_boss_arena.Init(map)


end

---darkrai_boss_arena.Enter(map)
--Engine callback function
function darkrai_boss_arena.Enter(map)

  GAME:FadeIn(20)

end

---darkrai_boss_arena.Exit(map)
--Engine callback function
function darkrai_boss_arena.Exit(map)


end

---darkrai_boss_arena.Update(map)
--Engine callback function
function darkrai_boss_arena.Update(map)


end

---darkrai_boss_arena.GameSave(map)
--Engine callback function
function darkrai_boss_arena.GameSave(map)


end

---darkrai_boss_arena.GameLoad(map)
--Engine callback function
function darkrai_boss_arena.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return darkrai_boss_arena

