--[[
    init.lua
    Created: 09/27/2024 22:17:31
    Description: Autogenerated script file for the map Temporal_Spire_Red_Sky.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Temporal_Spire_Red_Sky = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Temporal_Spire_Red_Sky.Init(map)
--Engine callback function
function Temporal_Spire_Red_Sky.Init(map)


end

---Temporal_Spire_Red_Sky.Enter(map)
--Engine callback function
function Temporal_Spire_Red_Sky.Enter(map)

  GAME:FadeIn(20)

end

---Temporal_Spire_Red_Sky.Exit(map)
--Engine callback function
function Temporal_Spire_Red_Sky.Exit(map)


end

---Temporal_Spire_Red_Sky.Update(map)
--Engine callback function
function Temporal_Spire_Red_Sky.Update(map)


end

---Temporal_Spire_Red_Sky.GameSave(map)
--Engine callback function
function Temporal_Spire_Red_Sky.GameSave(map)


end

---Temporal_Spire_Red_Sky.GameLoad(map)
--Engine callback function
function Temporal_Spire_Red_Sky.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Temporal_Spire_Red_Sky

