--[[
    init.lua
    Created: 09/06/2024 14:11:33
    Description: Autogenerated script file for the map crystal_lake_3.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crystal_lake_3 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_lake_3.Init(map)
--Engine callback function
function crystal_lake_3.Init(map)


end

---crystal_lake_3.Enter(map)
--Engine callback function
function crystal_lake_3.Enter(map)

  GAME:FadeIn(20)

end

---crystal_lake_3.Exit(map)
--Engine callback function
function crystal_lake_3.Exit(map)


end

---crystal_lake_3.Update(map)
--Engine callback function
function crystal_lake_3.Update(map)


end

---crystal_lake_3.GameSave(map)
--Engine callback function
function crystal_lake_3.GameSave(map)


end

---crystal_lake_3.GameLoad(map)
--Engine callback function
function crystal_lake_3.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_lake_3

