--[[
    init.lua
    Created: 09/26/2024 18:23:55
    Description: Autogenerated script file for the map Brine_Cave_Boss.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Brine_Cave_Boss = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Brine_Cave_Boss.Init(map)
--Engine callback function
function Brine_Cave_Boss.Init(map)


end

---Brine_Cave_Boss.Enter(map)
--Engine callback function
function Brine_Cave_Boss.Enter(map)

  GAME:FadeIn(20)

end

---Brine_Cave_Boss.Exit(map)
--Engine callback function
function Brine_Cave_Boss.Exit(map)


end

---Brine_Cave_Boss.Update(map)
--Engine callback function
function Brine_Cave_Boss.Update(map)


end

---Brine_Cave_Boss.GameSave(map)
--Engine callback function
function Brine_Cave_Boss.GameSave(map)


end

---Brine_Cave_Boss.GameLoad(map)
--Engine callback function
function Brine_Cave_Boss.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Brine_Cave_Boss

