--[[
    init.lua
    Created: 09/26/2024 20:26:29
    Description: Autogenerated script file for the map Old_Ruins_Stairs.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Old_Ruins_Stairs = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Old_Ruins_Stairs.Init(map)
--Engine callback function
function Old_Ruins_Stairs.Init(map)


end

---Old_Ruins_Stairs.Enter(map)
--Engine callback function
function Old_Ruins_Stairs.Enter(map)

  GAME:FadeIn(20)

end

---Old_Ruins_Stairs.Exit(map)
--Engine callback function
function Old_Ruins_Stairs.Exit(map)


end

---Old_Ruins_Stairs.Update(map)
--Engine callback function
function Old_Ruins_Stairs.Update(map)


end

---Old_Ruins_Stairs.GameSave(map)
--Engine callback function
function Old_Ruins_Stairs.GameSave(map)


end

---Old_Ruins_Stairs.GameLoad(map)
--Engine callback function
function Old_Ruins_Stairs.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Old_Ruins_Stairs

