--[[
    init.lua
    Created: 07/13/2024 15:58:03
    Description: Autogenerated script file for the map groudon_statue.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local groudon_statue = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---groudon_statue.Init(map)
--Engine callback function
function groudon_statue.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---groudon_statue.Enter(map)
--Engine callback function
function groudon_statue.Enter(map)

  GAME:FadeIn(20)

end

---groudon_statue.Exit(map)
--Engine callback function
function groudon_statue.Exit(map)


end

---groudon_statue.Update(map)
--Engine callback function
function groudon_statue.Update(map)


end

---groudon_statue.GameSave(map)
--Engine callback function
function groudon_statue.GameSave(map)


end

---groudon_statue.GameLoad(map)
--Engine callback function
function groudon_statue.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return groudon_statue

