--[[
    init.lua
    Created: 09/06/2024 22:10:13
    Description: Autogenerated script file for the map sealed_ruin_pit.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local sealed_ruin_pit = {}

-------------------------------
-- Map Callbacks
-------------------------------
---sealed_ruin_pit.Init(map)
--Engine callback function
function sealed_ruin_pit.Init(map)


end

---sealed_ruin_pit.Enter(map)
--Engine callback function
function sealed_ruin_pit.Enter(map)

  GAME:FadeIn(20)

end

---sealed_ruin_pit.Exit(map)
--Engine callback function
function sealed_ruin_pit.Exit(map)


end

---sealed_ruin_pit.Update(map)
--Engine callback function
function sealed_ruin_pit.Update(map)


end

---sealed_ruin_pit.GameSave(map)
--Engine callback function
function sealed_ruin_pit.GameSave(map)


end

---sealed_ruin_pit.GameLoad(map)
--Engine callback function
function sealed_ruin_pit.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return sealed_ruin_pit

