--[[
    init.lua
    Created: 09/06/2024 14:22:23
    Description: Autogenerated script file for the map crystal_cave_4.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crystal_cave_4 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_cave_4.Init(map)
--Engine callback function
function crystal_cave_4.Init(map)


end

---crystal_cave_4.Enter(map)
--Engine callback function
function crystal_cave_4.Enter(map)

  GAME:FadeIn(20)

end

---crystal_cave_4.Exit(map)
--Engine callback function
function crystal_cave_4.Exit(map)


end

---crystal_cave_4.Update(map)
--Engine callback function
function crystal_cave_4.Update(map)


end

---crystal_cave_4.GameSave(map)
--Engine callback function
function crystal_cave_4.GameSave(map)


end

---crystal_cave_4.GameLoad(map)
--Engine callback function
function crystal_cave_4.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_cave_4

