--[[
    init.lua
    Created: 09/03/2024 14:38:42
    Description: Autogenerated script file for the map northern_desert_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local northern_desert_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---northern_desert_entrance.Init(map)
--Engine callback function
function northern_desert_entrance.Init(map)


end

---northern_desert_entrance.Enter(map)
--Engine callback function
function northern_desert_entrance.Enter(map)

  GAME:FadeIn(20)

end

---northern_desert_entrance.Exit(map)
--Engine callback function
function northern_desert_entrance.Exit(map)


end

---northern_desert_entrance.Update(map)
--Engine callback function
function northern_desert_entrance.Update(map)


end

---northern_desert_entrance.GameSave(map)
--Engine callback function
function northern_desert_entrance.GameSave(map)


end

---northern_desert_entrance.GameLoad(map)
--Engine callback function
function northern_desert_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return northern_desert_entrance

