--[[
    init.lua
    Created: 07/12/2024 21:08:38
    Description: Autogenerated script file for the map mt_bristle_entrance.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local mt_bristle_entrance = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mt_bristle_entrance.Init(map)
--Engine callback function
function mt_bristle_entrance.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---mt_bristle_entrance.Enter(map)
--Engine callback function
function mt_bristle_entrance.Enter(map)

  GAME:FadeIn(20)

end

---mt_bristle_entrance.Exit(map)
--Engine callback function
function mt_bristle_entrance.Exit(map)


end

---mt_bristle_entrance.Update(map)
--Engine callback function
function mt_bristle_entrance.Update(map)


end

---mt_bristle_entrance.GameSave(map)
--Engine callback function
function mt_bristle_entrance.GameSave(map)


end

---mt_bristle_entrance.GameLoad(map)
--Engine callback function
function mt_bristle_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mt_bristle_entrance

