--[[
    init.lua
    Created: 07/07/2024 07:17:45
    Description: Autogenerated script file for the map crossroads_south.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local crossroads_south = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crossroads_south.Init(map)
--Engine callback function
function crossroads_south.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---crossroads_south.Enter(map)
--Engine callback function
function crossroads_south.Enter(map)

  GAME:FadeIn(20)

end

---crossroads_south.Exit(map)
--Engine callback function
function crossroads_south.Exit(map)


end

---crossroads_south.Update(map)
--Engine callback function
function crossroads_south.Update(map)


end

---crossroads_south.GameSave(map)
--Engine callback function
function crossroads_south.GameSave(map)


end

---crossroads_south.GameLoad(map)
--Engine callback function
function crossroads_south.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crossroads_south

