--[[
    init.lua
    Created: 07/11/2024 20:45:58
    Description: Autogenerated script file for the map drenched_bluff_end.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local drenched_bluff_end = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---drenched_bluff_end.Init(map)
--Engine callback function
function drenched_bluff_end.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---drenched_bluff_end.Enter(map)
--Engine callback function
function drenched_bluff_end.Enter(map)

  GAME:FadeIn(20)

end

---drenched_bluff_end.Exit(map)
--Engine callback function
function drenched_bluff_end.Exit(map)


end

---drenched_bluff_end.Update(map)
--Engine callback function
function drenched_bluff_end.Update(map)


end

---drenched_bluff_end.GameSave(map)
--Engine callback function
function drenched_bluff_end.GameSave(map)


end

---drenched_bluff_end.GameLoad(map)
--Engine callback function
function drenched_bluff_end.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return drenched_bluff_end

