--[[
    init.lua
    Created: 10/31/2023 15:01:40
    Description: Autogenerated script file for the map beach.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local beach = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---beach.Init(map)
--Engine callback function
function beach.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---beach.Enter(map)
--Engine callback function
function beach.Enter(map)

  --Normal Entry
  if not SV.beach.Cutscene then
	GAME:FadeIn(20)
	SOUND:FadeInSE("Beach_Noise", 20)
	--Handle NPCs based on progression
  else
	--Cutscenes
	if SV.Progression.Chapter == 1 then --1 cutscene in ch1
		beach.HeroPassesOut()
    end
  end
end

---beach.Exit(map)
--Engine callback function
function beach.Exit(map)
	
	local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(false, 20) end)
	local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Beach_Noise", 20) end)
	TASK:JoinCoroutines({coro1, coro2})

end

---beach.Update(map)
--Engine callback function
function beach.Update(map)


end

---beach.GameSave(map)
--Engine callback function
function beach.GameSave(map)


end

---beach.GameLoad(map)
--Engine callback function
function beach.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


-------------------------------
-- Cutscene Functions
-------------------------------

function beach.HeroPassesOut()
	GAME:FadeOut(false, 1)
	local player = CH('PLAYER')

	GAME:CutsceneMode(true)
	GROUND:CharSetAnim(player, "Laying", true)
		
	GAME:WaitFrames(120)
		
	SOUND:FadeInSE("Ambient/AMB_Ocean", 20)
		
	GAME:WaitFrames(60)
		
	UI:SetSpeaker('', false)
    UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_1']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_2']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_3']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_4']))
		
	GAME:WaitFrames(40)
		
	UI:WaitShowBG("OceanView", 25, 120)
    
	GAME:WaitFrames(60)
		
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_5']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_6']))
		
	UI:WaitHideBG(120)
	GAME:FadeIn(120)
		
	GAME:WaitFrames(20)
		
	UI:SetSpeaker('', false, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
	UI:SetSpeakerEmotion("Pain")
		
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_7']))
		
	GAME:WaitFrames(30)
		
	local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(false, 150) end)
	local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Ambient/AMB_Ocean", 150) end)
	TASK:JoinCoroutines({coro1, coro2})
		
	GAME:WaitFrames(60)
		
	GAME:EnterZone('cutscenes', -1, 5, 1)
		
	--GAME:RestartToTitle()
end

return beach

