--[[
    init.lua
    Created: 11/21/2023 17:42:59
    Description: Autogenerated script file for the map treasure_town.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local treasure_town = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---treasure_town.Init(map)
--Engine callback function
function treasure_town.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---treasure_town.Enter(map)
--Engine callback function
function treasure_town.Enter(map)

  GAME:FadeIn(20)

end

---treasure_town.Exit(map)
--Engine callback function
function treasure_town.Exit(map)


end

---treasure_town.Update(map)
--Engine callback function
function treasure_town.Update(map)


end

---treasure_town.GameSave(map)
--Engine callback function
function treasure_town.GameSave(map)


end

---treasure_town.GameLoad(map)
--Engine callback function
function treasure_town.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return treasure_town

