--[[
    init.lua
    Created: 09/26/2024 17:34:49
    Description: Autogenerated script file for the map Treeshroud_Forest_Entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Treeshroud_Forest_Entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Treeshroud_Forest_Entrance.Init(map)
--Engine callback function
function Treeshroud_Forest_Entrance.Init(map)


end

---Treeshroud_Forest_Entrance.Enter(map)
--Engine callback function
function Treeshroud_Forest_Entrance.Enter(map)

  GAME:FadeIn(20)

end

---Treeshroud_Forest_Entrance.Exit(map)
--Engine callback function
function Treeshroud_Forest_Entrance.Exit(map)


end

---Treeshroud_Forest_Entrance.Update(map)
--Engine callback function
function Treeshroud_Forest_Entrance.Update(map)


end

---Treeshroud_Forest_Entrance.GameSave(map)
--Engine callback function
function Treeshroud_Forest_Entrance.GameSave(map)


end

---Treeshroud_Forest_Entrance.GameLoad(map)
--Engine callback function
function Treeshroud_Forest_Entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Treeshroud_Forest_Entrance

