--[[
    init.lua
    Created: 09/03/2024 15:00:07
    Description: Autogenerated script file for the map crystal_cave_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crystal_cave_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_cave_entrance.Init(map)
--Engine callback function
function crystal_cave_entrance.Init(map)


end

---crystal_cave_entrance.Enter(map)
--Engine callback function
function crystal_cave_entrance.Enter(map)

  GAME:FadeIn(20)

end

---crystal_cave_entrance.Exit(map)
--Engine callback function
function crystal_cave_entrance.Exit(map)


end

---crystal_cave_entrance.Update(map)
--Engine callback function
function crystal_cave_entrance.Update(map)


end

---crystal_cave_entrance.GameSave(map)
--Engine callback function
function crystal_cave_entrance.GameSave(map)


end

---crystal_cave_entrance.GameLoad(map)
--Engine callback function
function crystal_cave_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_cave_entrance

