--[[
    init.lua
    Created: 09/06/2024 22:04:52
    Description: Autogenerated script file for the map sealed_ruin_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local sealed_ruin_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---sealed_ruin_entrance.Init(map)
--Engine callback function
function sealed_ruin_entrance.Init(map)


end

---sealed_ruin_entrance.Enter(map)
--Engine callback function
function sealed_ruin_entrance.Enter(map)

  GAME:FadeIn(20)

end

---sealed_ruin_entrance.Exit(map)
--Engine callback function
function sealed_ruin_entrance.Exit(map)


end

---sealed_ruin_entrance.Update(map)
--Engine callback function
function sealed_ruin_entrance.Update(map)


end

---sealed_ruin_entrance.GameSave(map)
--Engine callback function
function sealed_ruin_entrance.GameSave(map)


end

---sealed_ruin_entrance.GameLoad(map)
--Engine callback function
function sealed_ruin_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return sealed_ruin_entrance

