--[[
    init.lua
    Created: 10/05/2024 11:06:20
    Description: Autogenerated script file for the map aegis_cave_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local aegis_cave_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---aegis_cave_entrance.Init(map)
--Engine callback function
function aegis_cave_entrance.Init(map)


end

---aegis_cave_entrance.Enter(map)
--Engine callback function
function aegis_cave_entrance.Enter(map)

  GAME:FadeIn(20)

end

---aegis_cave_entrance.Exit(map)
--Engine callback function
function aegis_cave_entrance.Exit(map)


end

---aegis_cave_entrance.Update(map)
--Engine callback function
function aegis_cave_entrance.Update(map)


end

---aegis_cave_entrance.GameSave(map)
--Engine callback function
function aegis_cave_entrance.GameSave(map)


end

---aegis_cave_entrance.GameLoad(map)
--Engine callback function
function aegis_cave_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return aegis_cave_entrance

