--[[
    init.lua
    Created: 11/22/2023 13:29:41
    Description: Autogenerated script file for the map guild_outside_night.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local guild_outside_night = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_outside_night.Init(map)
--Engine callback function
function guild_outside_night.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---guild_outside_night.Enter(map)
--Engine callback function
function guild_outside_night.Enter(map)

  GAME:FadeIn(20)

end

---guild_outside_night.Exit(map)
--Engine callback function
function guild_outside_night.Exit(map)


end

---guild_outside_night.Update(map)
--Engine callback function
function guild_outside_night.Update(map)


end

---guild_outside_night.GameSave(map)
--Engine callback function
function guild_outside_night.GameSave(map)


end

---guild_outside_night.GameLoad(map)
--Engine callback function
function guild_outside_night.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return guild_outside_night

