--[[
    init.lua
    Created: 09/27/2024 21:33:12
    Description: Autogenerated script file for the map Temporal_Tower_Entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Temporal_Tower_Entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Temporal_Tower_Entrance.Init(map)
--Engine callback function
function Temporal_Tower_Entrance.Init(map)


end

---Temporal_Tower_Entrance.Enter(map)
--Engine callback function
function Temporal_Tower_Entrance.Enter(map)

  GAME:FadeIn(20)

end

---Temporal_Tower_Entrance.Exit(map)
--Engine callback function
function Temporal_Tower_Entrance.Exit(map)


end

---Temporal_Tower_Entrance.Update(map)
--Engine callback function
function Temporal_Tower_Entrance.Update(map)


end

---Temporal_Tower_Entrance.GameSave(map)
--Engine callback function
function Temporal_Tower_Entrance.GameSave(map)


end

---Temporal_Tower_Entrance.GameLoad(map)
--Engine callback function
function Temporal_Tower_Entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Temporal_Tower_Entrance

