--[[
    init.lua
    Created: 09/26/2024 18:35:01
    Description: Autogenerated script file for the map Hidden_Land_Entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Hidden_Land_Entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Hidden_Land_Entrance.Init(map)
--Engine callback function
function Hidden_Land_Entrance.Init(map)


end

---Hidden_Land_Entrance.Enter(map)
--Engine callback function
function Hidden_Land_Entrance.Enter(map)

  GAME:FadeIn(20)

end

---Hidden_Land_Entrance.Exit(map)
--Engine callback function
function Hidden_Land_Entrance.Exit(map)


end

---Hidden_Land_Entrance.Update(map)
--Engine callback function
function Hidden_Land_Entrance.Update(map)


end

---Hidden_Land_Entrance.GameSave(map)
--Engine callback function
function Hidden_Land_Entrance.GameSave(map)


end

---Hidden_Land_Entrance.GameLoad(map)
--Engine callback function
function Hidden_Land_Entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Hidden_Land_Entrance

