--[[
    init.lua
    Created: 09/03/2024 15:20:25
    Description: Autogenerated script file for the map crystal_cave_puzzle_unsolved.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crystal_cave_puzzle_unsolved = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_cave_puzzle_unsolved.Init(map)
--Engine callback function
function crystal_cave_puzzle_unsolved.Init(map)


end

---crystal_cave_puzzle_unsolved.Enter(map)
--Engine callback function
function crystal_cave_puzzle_unsolved.Enter(map)

  GAME:FadeIn(20)

end

---crystal_cave_puzzle_unsolved.Exit(map)
--Engine callback function
function crystal_cave_puzzle_unsolved.Exit(map)


end

---crystal_cave_puzzle_unsolved.Update(map)
--Engine callback function
function crystal_cave_puzzle_unsolved.Update(map)


end

---crystal_cave_puzzle_unsolved.GameSave(map)
--Engine callback function
function crystal_cave_puzzle_unsolved.GameSave(map)


end

---crystal_cave_puzzle_unsolved.GameLoad(map)
--Engine callback function
function crystal_cave_puzzle_unsolved.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_cave_puzzle_unsolved

