--[[
    init.lua
    Created: 07/07/2024 10:00:19
    Description: Autogenerated script file for the map habitat_sharpedo_bluff_day.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local habitat_sharpedo_bluff_day = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---habitat_sharpedo_bluff_day.Init(map)
--Engine callback function
function habitat_sharpedo_bluff_day.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---habitat_sharpedo_bluff_day.Enter(map)
--Engine callback function
function habitat_sharpedo_bluff_day.Enter(map)

  GAME:FadeIn(20)

end

---habitat_sharpedo_bluff_day.Exit(map)
--Engine callback function
function habitat_sharpedo_bluff_day.Exit(map)


end

---habitat_sharpedo_bluff_day.Update(map)
--Engine callback function
function habitat_sharpedo_bluff_day.Update(map)


end

---habitat_sharpedo_bluff_day.GameSave(map)
--Engine callback function
function habitat_sharpedo_bluff_day.GameSave(map)


end

---habitat_sharpedo_bluff_day.GameLoad(map)
--Engine callback function
function habitat_sharpedo_bluff_day.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return habitat_sharpedo_bluff_day

