--[[
    init.lua
    Created: 09/03/2024 13:22:28
    Description: Autogenerated script file for the map groudon_boss_arena.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local groudon_boss_arena = {}

-------------------------------
-- Map Callbacks
-------------------------------
---groudon_boss_arena.Init(map)
--Engine callback function
function groudon_boss_arena.Init(map)


end

---groudon_boss_arena.Enter(map)
--Engine callback function
function groudon_boss_arena.Enter(map)

  GAME:FadeIn(20)

end

---groudon_boss_arena.Exit(map)
--Engine callback function
function groudon_boss_arena.Exit(map)


end

---groudon_boss_arena.Update(map)
--Engine callback function
function groudon_boss_arena.Update(map)


end

---groudon_boss_arena.GameSave(map)
--Engine callback function
function groudon_boss_arena.GameSave(map)


end

---groudon_boss_arena.GameLoad(map)
--Engine callback function
function groudon_boss_arena.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return groudon_boss_arena

