--[[
    init.lua
    Created: 08/26/2024 18:37:00
    Description: Autogenerated script file for the map waterfall_cave_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local waterfall_cave_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---waterfall_cave_entrance.Init(map)
--Engine callback function
function waterfall_cave_entrance.Init(map)


end

---waterfall_cave_entrance.Enter(map)
--Engine callback function
function waterfall_cave_entrance.Enter(map)

  GAME:FadeIn(20)

end

---waterfall_cave_entrance.Exit(map)
--Engine callback function
function waterfall_cave_entrance.Exit(map)


end

---waterfall_cave_entrance.Update(map)
--Engine callback function
function waterfall_cave_entrance.Update(map)


end

---waterfall_cave_entrance.GameSave(map)
--Engine callback function
function waterfall_cave_entrance.GameSave(map)


end

---waterfall_cave_entrance.GameLoad(map)
--Engine callback function
function waterfall_cave_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return waterfall_cave_entrance

