--[[
    init.lua
    Created: 09/06/2024 12:26:11
    Description: Autogenerated script file for the map quicksand_cave_exterior.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local quicksand_cave_exterior = {}

-------------------------------
-- Map Callbacks
-------------------------------
---quicksand_cave_exterior.Init(map)
--Engine callback function
function quicksand_cave_exterior.Init(map)


end

---quicksand_cave_exterior.Enter(map)
--Engine callback function
function quicksand_cave_exterior.Enter(map)

  GAME:FadeIn(20)

end

---quicksand_cave_exterior.Exit(map)
--Engine callback function
function quicksand_cave_exterior.Exit(map)


end

---quicksand_cave_exterior.Update(map)
--Engine callback function
function quicksand_cave_exterior.Update(map)


end

---quicksand_cave_exterior.GameSave(map)
--Engine callback function
function quicksand_cave_exterior.GameSave(map)


end

---quicksand_cave_exterior.GameLoad(map)
--Engine callback function
function quicksand_cave_exterior.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return quicksand_cave_exterior

