--[[
    init.lua
    Created: 12/04/2023 12:47:19
    Description: Autogenerated script file for the map storm_cutscene_b.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local storm_cutscene_b = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---storm_cutscene_b.Init(map)
--Engine callback function
function storm_cutscene_b.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---storm_cutscene_b.Enter(map)
--Engine callback function
function storm_cutscene_b.Enter(map)

  GROUND:Hide("PLAYER")

  local coro1 = TASK:BranchCoroutine(function() GAME:FadeIn(60) end)
  local coro2 = TASK:BranchCoroutine(function() SOUND:FadeInSE("Ambient/AMB_Storm", 60) end)
  TASK:JoinCoroutines({coro1, coro2})
  
  GAME:WaitFrames(360)
  
  GAME:FadeOut(false, 60)
  
  --next scene
  GAME:EnterGroundMap("storm_cutscene_c", "Entrance")

end

---storm_cutscene_b.Exit(map)
--Engine callback function
function storm_cutscene_b.Exit(map)


end

---storm_cutscene_b.Update(map)
--Engine callback function
function storm_cutscene_b.Update(map)


end

---storm_cutscene_b.GameSave(map)
--Engine callback function
function storm_cutscene_b.GameSave(map)


end

---storm_cutscene_b.GameLoad(map)
--Engine callback function
function storm_cutscene_b.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return storm_cutscene_b

