--[[
    init.lua
    Created: 09/06/2024 14:35:04
    Description: Autogenerated script file for the map chasm_cave_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local chasm_cave_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---chasm_cave_entrance.Init(map)
--Engine callback function
function chasm_cave_entrance.Init(map)


end

---chasm_cave_entrance.Enter(map)
--Engine callback function
function chasm_cave_entrance.Enter(map)

  GAME:FadeIn(20)

end

---chasm_cave_entrance.Exit(map)
--Engine callback function
function chasm_cave_entrance.Exit(map)


end

---chasm_cave_entrance.Update(map)
--Engine callback function
function chasm_cave_entrance.Update(map)


end

---chasm_cave_entrance.GameSave(map)
--Engine callback function
function chasm_cave_entrance.GameSave(map)


end

---chasm_cave_entrance.GameLoad(map)
--Engine callback function
function chasm_cave_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return chasm_cave_entrance

