--[[
    init.lua
    Created: 09/27/2024 21:17:26
    Description: Autogenerated script file for the map Rainbow_Stoneship_East.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Rainbow_Stoneship_East = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Rainbow_Stoneship_East.Init(map)
--Engine callback function
function Rainbow_Stoneship_East.Init(map)


end

---Rainbow_Stoneship_East.Enter(map)
--Engine callback function
function Rainbow_Stoneship_East.Enter(map)

  GAME:FadeIn(20)

end

---Rainbow_Stoneship_East.Exit(map)
--Engine callback function
function Rainbow_Stoneship_East.Exit(map)


end

---Rainbow_Stoneship_East.Update(map)
--Engine callback function
function Rainbow_Stoneship_East.Update(map)


end

---Rainbow_Stoneship_East.GameSave(map)
--Engine callback function
function Rainbow_Stoneship_East.GameSave(map)


end

---Rainbow_Stoneship_East.GameLoad(map)
--Engine callback function
function Rainbow_Stoneship_East.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Rainbow_Stoneship_East

