--[[
    init.lua
    Created: 09/27/2024 21:10:48
    Description: Autogenerated script file for the map Rainbow_Stoneship_On_Ground.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Rainbow_Stoneship_On_Ground = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Rainbow_Stoneship_On_Ground.Init(map)
--Engine callback function
function Rainbow_Stoneship_On_Ground.Init(map)


end

---Rainbow_Stoneship_On_Ground.Enter(map)
--Engine callback function
function Rainbow_Stoneship_On_Ground.Enter(map)

  GAME:FadeIn(20)

end

---Rainbow_Stoneship_On_Ground.Exit(map)
--Engine callback function
function Rainbow_Stoneship_On_Ground.Exit(map)


end

---Rainbow_Stoneship_On_Ground.Update(map)
--Engine callback function
function Rainbow_Stoneship_On_Ground.Update(map)


end

---Rainbow_Stoneship_On_Ground.GameSave(map)
--Engine callback function
function Rainbow_Stoneship_On_Ground.GameSave(map)


end

---Rainbow_Stoneship_On_Ground.GameLoad(map)
--Engine callback function
function Rainbow_Stoneship_On_Ground.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Rainbow_Stoneship_On_Ground

