--[[
    init.lua
    Created: 09/26/2024 18:17:34
    Description: Autogenerated script file for the map Brine_Cave_Pit.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Brine_Cave_Pit = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Brine_Cave_Pit.Init(map)
--Engine callback function
function Brine_Cave_Pit.Init(map)


end

---Brine_Cave_Pit.Enter(map)
--Engine callback function
function Brine_Cave_Pit.Enter(map)

  GAME:FadeIn(20)

end

---Brine_Cave_Pit.Exit(map)
--Engine callback function
function Brine_Cave_Pit.Exit(map)


end

---Brine_Cave_Pit.Update(map)
--Engine callback function
function Brine_Cave_Pit.Update(map)


end

---Brine_Cave_Pit.GameSave(map)
--Engine callback function
function Brine_Cave_Pit.GameSave(map)


end

---Brine_Cave_Pit.GameLoad(map)
--Engine callback function
function Brine_Cave_Pit.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Brine_Cave_Pit

