--[[
    init.lua
    Created: 11/22/2023 13:44:42
    Description: Autogenerated script file for the map marowak_dojo_final_maze.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local marowak_dojo_final_maze = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---marowak_dojo_final_maze.Init(map)
--Engine callback function
function marowak_dojo_final_maze.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---marowak_dojo_final_maze.Enter(map)
--Engine callback function
function marowak_dojo_final_maze.Enter(map)

  GAME:FadeIn(20)

end

---marowak_dojo_final_maze.Exit(map)
--Engine callback function
function marowak_dojo_final_maze.Exit(map)


end

---marowak_dojo_final_maze.Update(map)
--Engine callback function
function marowak_dojo_final_maze.Update(map)


end

---marowak_dojo_final_maze.GameSave(map)
--Engine callback function
function marowak_dojo_final_maze.GameSave(map)


end

---marowak_dojo_final_maze.GameLoad(map)
--Engine callback function
function marowak_dojo_final_maze.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return marowak_dojo_final_maze

