--[[
    init.lua
    Created: 11/22/2023 12:14:44
    Description: Autogenerated script file for the map guild_outside.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local guild_outside = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_outside.Init(map)
--Engine callback function
function guild_outside.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---guild_outside.Enter(map)
--Engine callback function
function guild_outside.Enter(map)

  GAME:FadeIn(20)

end

---guild_outside.Exit(map)
--Engine callback function
function guild_outside.Exit(map)


end

---guild_outside.Update(map)
--Engine callback function
function guild_outside.Update(map)


end

---guild_outside.GameSave(map)
--Engine callback function
function guild_outside.GameSave(map)


end

---guild_outside.GameLoad(map)
--Engine callback function
function guild_outside.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return guild_outside

