--[[
    init.lua
    Created: 10/05/2024 11:21:49
    Description: Autogenerated script file for the map deep_aegis_cave_regigigas_boss_arena.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local deep_aegis_cave_regigigas_boss_arena = {}

-------------------------------
-- Map Callbacks
-------------------------------
---deep_aegis_cave_regigigas_boss_arena.Init(map)
--Engine callback function
function deep_aegis_cave_regigigas_boss_arena.Init(map)


end

---deep_aegis_cave_regigigas_boss_arena.Enter(map)
--Engine callback function
function deep_aegis_cave_regigigas_boss_arena.Enter(map)

  GAME:FadeIn(20)

end

---deep_aegis_cave_regigigas_boss_arena.Exit(map)
--Engine callback function
function deep_aegis_cave_regigigas_boss_arena.Exit(map)


end

---deep_aegis_cave_regigigas_boss_arena.Update(map)
--Engine callback function
function deep_aegis_cave_regigigas_boss_arena.Update(map)


end

---deep_aegis_cave_regigigas_boss_arena.GameSave(map)
--Engine callback function
function deep_aegis_cave_regigigas_boss_arena.GameSave(map)


end

---deep_aegis_cave_regigigas_boss_arena.GameLoad(map)
--Engine callback function
function deep_aegis_cave_regigigas_boss_arena.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return deep_aegis_cave_regigigas_boss_arena

