--[[
    init.lua
    Created: 07/06/2024 18:21:40
    Description: Autogenerated script file for the map crossroads.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crossroads = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---crossroads.Init(map)
--Engine callback function
function crossroads.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---crossroads.Enter(map)
--Engine callback function
function crossroads.Enter(map)

  GAME:FadeIn(20)

end

---crossroads.Exit(map)
--Engine callback function
function crossroads.Exit(map)


end

---crossroads.Update(map)
--Engine callback function
function crossroads.Update(map)


end

---crossroads.GameSave(map)
--Engine callback function
function crossroads.GameSave(map)


end

---crossroads.GameLoad(map)
--Engine callback function
function crossroads.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crossroads

