--[[
    init.lua
    Created: 10/05/2024 11:30:42
    Description: Autogenerated script file for the map mt_travail_peak.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local mt_travail_peak = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mt_travail_peak.Init(map)
--Engine callback function
function mt_travail_peak.Init(map)


end

---mt_travail_peak.Enter(map)
--Engine callback function
function mt_travail_peak.Enter(map)

  GAME:FadeIn(20)

end

---mt_travail_peak.Exit(map)
--Engine callback function
function mt_travail_peak.Exit(map)


end

---mt_travail_peak.Update(map)
--Engine callback function
function mt_travail_peak.Update(map)


end

---mt_travail_peak.GameSave(map)
--Engine callback function
function mt_travail_peak.GameSave(map)


end

---mt_travail_peak.GameLoad(map)
--Engine callback function
function mt_travail_peak.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mt_travail_peak

