--[[
    init.lua
    Created: 09/26/2024 17:43:35
    Description: Autogenerated script file for the map Treeshroud_Forest_End_Paralysis.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Treeshroud_Forest_End_Paralysis = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Treeshroud_Forest_End_Paralysis.Init(map)
--Engine callback function
function Treeshroud_Forest_End_Paralysis.Init(map)


end

---Treeshroud_Forest_End_Paralysis.Enter(map)
--Engine callback function
function Treeshroud_Forest_End_Paralysis.Enter(map)

  GAME:FadeIn(20)

end

---Treeshroud_Forest_End_Paralysis.Exit(map)
--Engine callback function
function Treeshroud_Forest_End_Paralysis.Exit(map)


end

---Treeshroud_Forest_End_Paralysis.Update(map)
--Engine callback function
function Treeshroud_Forest_End_Paralysis.Update(map)


end

---Treeshroud_Forest_End_Paralysis.GameSave(map)
--Engine callback function
function Treeshroud_Forest_End_Paralysis.GameSave(map)


end

---Treeshroud_Forest_End_Paralysis.GameLoad(map)
--Engine callback function
function Treeshroud_Forest_End_Paralysis.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Treeshroud_Forest_End_Paralysis

