--[[
    init.lua
    Created: 09/26/2024 18:09:22
    Description: Autogenerated script file for the map Brine_Cave_Entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Brine_Cave_Entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Brine_Cave_Entrance.Init(map)
--Engine callback function
function Brine_Cave_Entrance.Init(map)


end

---Brine_Cave_Entrance.Enter(map)
--Engine callback function
function Brine_Cave_Entrance.Enter(map)

  GAME:FadeIn(20)

end

---Brine_Cave_Entrance.Exit(map)
--Engine callback function
function Brine_Cave_Entrance.Exit(map)


end

---Brine_Cave_Entrance.Update(map)
--Engine callback function
function Brine_Cave_Entrance.Update(map)


end

---Brine_Cave_Entrance.GameSave(map)
--Engine callback function
function Brine_Cave_Entrance.GameSave(map)


end

---Brine_Cave_Entrance.GameLoad(map)
--Engine callback function
function Brine_Cave_Entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Brine_Cave_Entrance

