--[[
    init.lua
    Created: 09/06/2024 22:47:49
    Description: Autogenerated script file for the map deep_dusk_forest_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local deep_dusk_forest_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---deep_dusk_forest_entrance.Init(map)
--Engine callback function
function deep_dusk_forest_entrance.Init(map)


end

---deep_dusk_forest_entrance.Enter(map)
--Engine callback function
function deep_dusk_forest_entrance.Enter(map)

  GAME:FadeIn(20)

end

---deep_dusk_forest_entrance.Exit(map)
--Engine callback function
function deep_dusk_forest_entrance.Exit(map)


end

---deep_dusk_forest_entrance.Update(map)
--Engine callback function
function deep_dusk_forest_entrance.Update(map)


end

---deep_dusk_forest_entrance.GameSave(map)
--Engine callback function
function deep_dusk_forest_entrance.GameSave(map)


end

---deep_dusk_forest_entrance.GameLoad(map)
--Engine callback function
function deep_dusk_forest_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return deep_dusk_forest_entrance

