--[[
    init.lua
    Created: 07/06/2024 18:21:40
    Description: Autogenerated script file for the map crossroads_assembly.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crossroads_assembly = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---crossroads.Init(map)
--Engine callback function
function crossroads_assembly.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---crossroads_assembly.Enter(map)
--Engine callback function
function crossroads_assembly.Enter(map)

  GAME:FadeIn(20)

end

---crossroads_assembly.Exit(map)
--Engine callback function
function crossroads_assembly.Exit(map)


end

---crossroads_assembly.Update(map)
--Engine callback function
function crossroads_assembly.Update(map)


end

---crossroads_assembly.GameSave(map)
--Engine callback function
function crossroads_assembly.GameSave(map)


end

---crossroads_assembly.GameLoad(map)
--Engine callback function
function crossroads_assembly.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crossroads_assembly

