--[[
    init.lua
    Created: 09/06/2024 14:25:31
    Description: Autogenerated script file for the map crystal_cave_5.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crystal_cave_5 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_cave_5.Init(map)
--Engine callback function
function crystal_cave_5.Init(map)


end

---crystal_cave_5.Enter(map)
--Engine callback function
function crystal_cave_5.Enter(map)

  GAME:FadeIn(20)

end

---crystal_cave_5.Exit(map)
--Engine callback function
function crystal_cave_5.Exit(map)


end

---crystal_cave_5.Update(map)
--Engine callback function
function crystal_cave_5.Update(map)


end

---crystal_cave_5.GameSave(map)
--Engine callback function
function crystal_cave_5.GameSave(map)


end

---crystal_cave_5.GameLoad(map)
--Engine callback function
function crystal_cave_5.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_cave_5

