--[[
    init.lua
    Created: 09/27/2024 22:25:07
    Description: Autogenerated script file for the map Temporal_Spire_Restored.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Temporal_Spire_Restored = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Temporal_Spire_Restored.Init(map)
--Engine callback function
function Temporal_Spire_Restored.Init(map)


end

---Temporal_Spire_Restored.Enter(map)
--Engine callback function
function Temporal_Spire_Restored.Enter(map)

  GAME:FadeIn(20)

end

---Temporal_Spire_Restored.Exit(map)
--Engine callback function
function Temporal_Spire_Restored.Exit(map)


end

---Temporal_Spire_Restored.Update(map)
--Engine callback function
function Temporal_Spire_Restored.Update(map)


end

---Temporal_Spire_Restored.GameSave(map)
--Engine callback function
function Temporal_Spire_Restored.GameSave(map)


end

---Temporal_Spire_Restored.GameLoad(map)
--Engine callback function
function Temporal_Spire_Restored.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Temporal_Spire_Restored

