--[[
    init.lua
    Created: 09/06/2024 12:46:31
    Description: Autogenerated script file for the map quicksand_cave_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local quicksand_cave_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---quicksand_cave_entrance.Init(map)
--Engine callback function
function quicksand_cave_entrance.Init(map)


end

---quicksand_cave_entrance.Enter(map)
--Engine callback function
function quicksand_cave_entrance.Enter(map)

  GAME:FadeIn(20)

end

---quicksand_cave_entrance.Exit(map)
--Engine callback function
function quicksand_cave_entrance.Exit(map)


end

---quicksand_cave_entrance.Update(map)
--Engine callback function
function quicksand_cave_entrance.Update(map)


end

---quicksand_cave_entrance.GameSave(map)
--Engine callback function
function quicksand_cave_entrance.GameSave(map)


end

---quicksand_cave_entrance.GameLoad(map)
--Engine callback function
function quicksand_cave_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return quicksand_cave_entrance

