--[[
    init.lua
    Created: 08/27/2024 19:52:05
    Description: Autogenerated script file for the map upper_steam_cave_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local upper_steam_cave_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---upper_steam_cave_entrance.Init(map)
--Engine callback function
function upper_steam_cave_entrance.Init(map)


end

---upper_steam_cave_entrance.Enter(map)
--Engine callback function
function upper_steam_cave_entrance.Enter(map)

  GAME:FadeIn(20)

end

---upper_steam_cave_entrance.Exit(map)
--Engine callback function
function upper_steam_cave_entrance.Exit(map)


end

---upper_steam_cave_entrance.Update(map)
--Engine callback function
function upper_steam_cave_entrance.Update(map)


end

---upper_steam_cave_entrance.GameSave(map)
--Engine callback function
function upper_steam_cave_entrance.GameSave(map)


end

---upper_steam_cave_entrance.GameLoad(map)
--Engine callback function
function upper_steam_cave_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return upper_steam_cave_entrance

