--[[
    init.lua
    Created: 10/05/2024 10:37:23
    Description: Autogenerated script file for the map mystifying_forest_pit.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local mystifying_forest_pit = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mystifying_forest_pit.Init(map)
--Engine callback function
function mystifying_forest_pit.Init(map)


end

---mystifying_forest_pit.Enter(map)
--Engine callback function
function mystifying_forest_pit.Enter(map)

  GAME:FadeIn(20)

end

---mystifying_forest_pit.Exit(map)
--Engine callback function
function mystifying_forest_pit.Exit(map)


end

---mystifying_forest_pit.Update(map)
--Engine callback function
function mystifying_forest_pit.Update(map)


end

---mystifying_forest_pit.GameSave(map)
--Engine callback function
function mystifying_forest_pit.GameSave(map)


end

---mystifying_forest_pit.GameLoad(map)
--Engine callback function
function mystifying_forest_pit.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mystifying_forest_pit

