--[[
    init.lua
    Created: 09/06/2024 14:02:58
    Description: Autogenerated script file for the map crystal_lake_2.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local crystal_lake_2 = {}

-------------------------------
-- Map Callbacks
-------------------------------
---crystal_lake_2.Init(map)
--Engine callback function
function crystal_lake_2.Init(map)


end

---crystal_lake_2.Enter(map)
--Engine callback function
function crystal_lake_2.Enter(map)

  GAME:FadeIn(20)

end

---crystal_lake_2.Exit(map)
--Engine callback function
function crystal_lake_2.Exit(map)


end

---crystal_lake_2.Update(map)
--Engine callback function
function crystal_lake_2.Update(map)


end

---crystal_lake_2.GameSave(map)
--Engine callback function
function crystal_lake_2.GameSave(map)


end

---crystal_lake_2.GameLoad(map)
--Engine callback function
function crystal_lake_2.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return crystal_lake_2

