--[[
    init.lua
    Created: 09/26/2024 19:34:26
    Description: Autogenerated script file for the map Legendary_Hallway.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local Legendary_Hallway = {}

-------------------------------
-- Map Callbacks
-------------------------------
---Legendary_Hallway.Init(map)
--Engine callback function
function Legendary_Hallway.Init(map)


end

---Legendary_Hallway.Enter(map)
--Engine callback function
function Legendary_Hallway.Enter(map)

  GAME:FadeIn(20)

end

---Legendary_Hallway.Exit(map)
--Engine callback function
function Legendary_Hallway.Exit(map)


end

---Legendary_Hallway.Update(map)
--Engine callback function
function Legendary_Hallway.Update(map)


end

---Legendary_Hallway.GameSave(map)
--Engine callback function
function Legendary_Hallway.GameSave(map)


end

---Legendary_Hallway.GameLoad(map)
--Engine callback function
function Legendary_Hallway.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return Legendary_Hallway

