--[[
    init.lua
    Created: 10/05/2024 11:00:53
    Description: Autogenerated script file for the map mystifying_forest_guild_boss_arena.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local mystifying_forest_guild_boss_arena = {}

-------------------------------
-- Map Callbacks
-------------------------------
---mystifying_forest_guild_boss_arena.Init(map)
--Engine callback function
function mystifying_forest_guild_boss_arena.Init(map)


end

---mystifying_forest_guild_boss_arena.Enter(map)
--Engine callback function
function mystifying_forest_guild_boss_arena.Enter(map)

  GAME:FadeIn(20)

end

---mystifying_forest_guild_boss_arena.Exit(map)
--Engine callback function
function mystifying_forest_guild_boss_arena.Exit(map)


end

---mystifying_forest_guild_boss_arena.Update(map)
--Engine callback function
function mystifying_forest_guild_boss_arena.Update(map)


end

---mystifying_forest_guild_boss_arena.GameSave(map)
--Engine callback function
function mystifying_forest_guild_boss_arena.GameSave(map)


end

---mystifying_forest_guild_boss_arena.GameLoad(map)
--Engine callback function
function mystifying_forest_guild_boss_arena.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return mystifying_forest_guild_boss_arena

