--[[
    init.lua
    Created: 12/04/2023 12:47:19
    Description: Autogenerated script file for the map storm_cutscene_a.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local storm_cutscene_a = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---storm_cutscene_a.Init(map)
--Engine callback function
function storm_cutscene_a.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---storm_cutscene_a.Enter(map)
--Engine callback function
function storm_cutscene_a.Enter(map)

  GROUND:Hide("PLAYER")
  UI:ResetSpeaker()
  
  SOUND:FadeInSE("Ambient/AMB_Storm", 120)
  
  --lightning sfx
  SOUND:PlaySE("Battle/EVT_CH01_Thunder")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)
  SOUND:PlaySE("Battle/EVT_CH01_Thunder")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)
  
  GAME:WaitFrames(10)
  
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Unknown_1']))
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Unknown_2']))
  
  --lightning
  SOUND:PlaySE("Battle/EVT_CH01_Thunder")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)
  
  GAME:WaitFrames(10)
  
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Unknown_3']))
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Unknown_4']))
  
  --lightning
  SOUND:PlaySE("Battle/EVT_CH01_Thunder")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)
  
  GAME:WaitFrames(10)
  
  UI:WaitShowDialogue(STRINGS:Format(MapStrings['Unknown_5']))

  --lightning sfx
  SOUND:PlaySE("Battle/EVT_CH01_Thunder_2")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)
  SOUND:PlaySE("Battle/EVT_CH01_Thunder_2")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)

GAME:WaitFrames(10)

--lightning sfx
SOUND:PlaySE("Battle/EVT_CH01_Thunder_2")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)
  SOUND:PlaySE("Battle/EVT_CH01_Thunder_2")
  GAME:FadeOut(true, 1)
  GAME:WaitFrames(5)
  GAME:FadeIn(1)
  GAME:WaitFrames(5)
  
  GAME:WaitFrames(10)
  
  --transition
  SOUND:PlaySE("Battle/EVT_CH01_Transition")
  local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(true, 120) end)
  local coro2 = TASK:BranchCoroutine(function() UI:WaitShowTimedDialogue(STRINGS:Format(MapStrings['Unknown_6']), 120) end)
  local coro3 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Ambient/AMB_Storm", 120) end)
  TASK:JoinCoroutines({coro1, coro2, coro3})
  
  GAME:WaitFrames(180)
  
  GAME:FadeIn(60)
  
  GAME:WaitFrames(60)
  
  --next scene
  GAME:FadeOut(false, 1)
  GAME:EnterGroundMap("storm_cutscene_b", "Entrance")

end

---storm_cutscene_a.Exit(map)
--Engine callback function
function storm_cutscene_a.Exit(map)


end

---storm_cutscene_a.Update(map)
--Engine callback function
function storm_cutscene_a.Update(map)


end

---storm_cutscene_a.GameSave(map)
--Engine callback function
function storm_cutscene_a.GameSave(map)


end

---storm_cutscene_a.GameLoad(map)
--Engine callback function
function storm_cutscene_a.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return storm_cutscene_a

