--[[
    init.lua
    Created: 10/05/2024 11:34:22
    Description: Autogenerated script file for the map dark_crater_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local dark_crater_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---dark_crater_entrance.Init(map)
--Engine callback function
function dark_crater_entrance.Init(map)


end

---dark_crater_entrance.Enter(map)
--Engine callback function
function dark_crater_entrance.Enter(map)

  GAME:FadeIn(20)

end

---dark_crater_entrance.Exit(map)
--Engine callback function
function dark_crater_entrance.Exit(map)


end

---dark_crater_entrance.Update(map)
--Engine callback function
function dark_crater_entrance.Update(map)


end

---dark_crater_entrance.GameSave(map)
--Engine callback function
function dark_crater_entrance.GameSave(map)


end

---dark_crater_entrance.GameLoad(map)
--Engine callback function
function dark_crater_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return dark_crater_entrance

