--[[
    init.lua
    Created: 09/03/2024 13:52:01
    Description: Autogenerated script file for the map far_amp_plains_boss_arena.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local far_amp_plains_boss_arena = {}

-------------------------------
-- Map Callbacks
-------------------------------
---far_amp_plains_boss_arena.Init(map)
--Engine callback function
function far_amp_plains_boss_arena.Init(map)


end

---far_amp_plains_boss_arena.Enter(map)
--Engine callback function
function far_amp_plains_boss_arena.Enter(map)

  GAME:FadeIn(20)

end

---far_amp_plains_boss_arena.Exit(map)
--Engine callback function
function far_amp_plains_boss_arena.Exit(map)


end

---far_amp_plains_boss_arena.Update(map)
--Engine callback function
function far_amp_plains_boss_arena.Update(map)


end

---far_amp_plains_boss_arena.GameSave(map)
--Engine callback function
function far_amp_plains_boss_arena.GameSave(map)


end

---far_amp_plains_boss_arena.GameLoad(map)
--Engine callback function
function far_amp_plains_boss_arena.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return far_amp_plains_boss_arena

